FROM node:20
WORKDIR /app

# Copy dependency files first
COPY package*.json ./

# Install all dependencies
RUN npm install

# Copy source files
COPY . .

# Expose the Angular dev server port
EXPOSE 4200

# Run the dev server (listen on all interfaces)
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--proxy-config", "proxy.conf.json"]